<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDKuKPox\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDKuKPox/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDKuKPox.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDKuKPox\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDKuKPox\App_KernelDevDebugContainer([
    'container.build_hash' => 'DKuKPox',
    'container.build_id' => 'ab5fb26e',
    'container.build_time' => 1680835516,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDKuKPox');
